function _1 () {
    display.setMatrixColor(2, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(0, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(0, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(1, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
}
GAME_ZIP64.onButtonPress(GAME_ZIP64.ZIP64ButtonPins.Up, GAME_ZIP64.ZIP64ButtonEvents.Down, function () {
    display.show()
    _1()
})
let display: GAME_ZIP64.ZIP64Display = null
display = GAME_ZIP64.createZIP64Display()
display.setBrightness(50)
basic.forever(function () {
	
})
