function _7 () {
    display.setMatrixColor(2, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _2 () {
    display.setMatrixColor(3, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(1, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _6 () {
    display.setMatrixColor(3, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _9 () {
    display.setMatrixColor(1, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(0, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(0, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(0, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(0, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(6, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(7, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(7, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(5, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(6, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(7, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(7, 3, GAME_ZIP64.colors(ZipLedColors.White))
}
function _5 () {
    display.setMatrixColor(4, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _3 () {
    display.setMatrixColor(3, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(1, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _8 () {
    display.setMatrixColor(2, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(1, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(6, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(7, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(7, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(7, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(7, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(6, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _4 () {
    display.setMatrixColor(4, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(2, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(2, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
}
function _1 () {
    display.setMatrixColor(2, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 1, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 2, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 3, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 4, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(1, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(5, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(6, 5, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(2, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(3, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 6, GAME_ZIP64.colors(ZipLedColors.Orange))
    display.setMatrixColor(4, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 0, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(0, 4, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(0, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(1, 6, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(3, 5, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(5, 3, GAME_ZIP64.colors(ZipLedColors.Yellow))
    display.setMatrixColor(2, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 1, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 2, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 3, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 4, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(7, 5, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(6, 6, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(5, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(4, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(3, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(2, 7, GAME_ZIP64.rgb(150, 88, 42))
    display.setMatrixColor(0, 3, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(0, 2, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(1, 1, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(2, 0, GAME_ZIP64.colors(ZipLedColors.White))
    display.setMatrixColor(3, 0, GAME_ZIP64.colors(ZipLedColors.White))
}
GAME_ZIP64.onButtonPress(GAME_ZIP64.ZIP64ButtonPins.Up, GAME_ZIP64.ZIP64ButtonEvents.Down, function () {
	
})
let display: GAME_ZIP64.ZIP64Display = null
display = GAME_ZIP64.createZIP64Display()
display.setBrightness(20)
basic.forever(function () {
	
})
basic.forever(function () {
    _1()
    display.show()
    basic.pause(100)
    display.clear()
    _2()
    display.show()
    basic.pause(100)
    display.clear()
    _3()
    display.show()
    basic.pause(100)
    display.clear()
    _4()
    display.show()
    basic.pause(100)
    display.clear()
    _5()
    display.show()
    basic.pause(100)
    display.clear()
    _6()
    display.show()
    basic.pause(100)
    display.clear()
    _7()
    display.show()
    basic.pause(100)
    display.clear()
    _8()
    display.show()
    basic.pause(100)
    display.clear()
    _9()
    display.show()
    basic.pause(100)
    display.clear()
})
